#include "AAudioLoader.h"

Map<UInt32, DWORD>	AAudioLoader::m_ChannelCountToChannelMaskMap;

void	AAudioLoader::InitializeChannelMaskMap() {
	m_ChannelCountToChannelMaskMap.Add(1U, SPEAKER_FRONT_CENTER);
	m_ChannelCountToChannelMaskMap.Add(2U, SPEAKER_FRONT_LEFT | SPEAKER_FRONT_RIGHT);
	m_ChannelCountToChannelMaskMap.Add(3U, SPEAKER_FRONT_LEFT | SPEAKER_FRONT_RIGHT | SPEAKER_BACK_CENTER);
	m_ChannelCountToChannelMaskMap.Add(4U, SPEAKER_FRONT_LEFT | SPEAKER_FRONT_RIGHT | SPEAKER_BACK_LEFT | SPEAKER_BACK_RIGHT);
	m_ChannelCountToChannelMaskMap.Add(5U, SPEAKER_FRONT_LEFT | SPEAKER_FRONT_RIGHT | SPEAKER_FRONT_CENTER | SPEAKER_BACK_LEFT | SPEAKER_BACK_RIGHT);
	m_ChannelCountToChannelMaskMap.Add(6U, SPEAKER_FRONT_LEFT | SPEAKER_FRONT_RIGHT | SPEAKER_FRONT_CENTER | SPEAKER_LOW_FREQUENCY | SPEAKER_BACK_LEFT | SPEAKER_BACK_RIGHT);
	m_ChannelCountToChannelMaskMap.Add(7U, SPEAKER_FRONT_LEFT | SPEAKER_FRONT_RIGHT | SPEAKER_FRONT_CENTER | SPEAKER_LOW_FREQUENCY | SPEAKER_SIDE_LEFT | SPEAKER_SIDE_RIGHT | SPEAKER_BACK_CENTER);
	m_ChannelCountToChannelMaskMap.Add(8U, SPEAKER_FRONT_LEFT | SPEAKER_FRONT_RIGHT | SPEAKER_FRONT_CENTER | SPEAKER_LOW_FREQUENCY | SPEAKER_SIDE_LEFT | SPEAKER_SIDE_RIGHT | SPEAKER_BACK_LEFT | SPEAKER_BACK_RIGHT);
}

struct InitAAudioLoaderMap {
	InitAAudioLoaderMap() {
		AAudioLoader::InitializeChannelMaskMap();
	}
};
InitAAudioLoaderMap initAAudioLoaderMapInstance;